##!/bin/bash
#source ./common.sh
#
#echo Copy MongoDB repo file
#cp mongo.repo /etc/yum.repos.d/mongo.repo &>>log_file
#Status_Print $?
#
#echo Install MongoDB
#dnf install mongodb-org -y &>>log_file
#Status_Print $?
#
#echo Update MongoDB listen address
#sed -i 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf &>>log_file
#Status_Print $?
#
#echo Start MongoDB Service
#systemctl enable mongod &>>log_file
#systemctl restart mongod &>>log_file
#Status_Print $?


- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed

- name: Update listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start MongoDB service
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: true
