- name: Disable nginx Default version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable nginx 1.24 version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install the latest version of nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy nginx configuration file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove nginx directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Created nginx directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and extract frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start nginx service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true





















#dnf module disable nginx -y &>>log_file
#Status_Print $?
#
#dnf module enable nginx:1.24 -y &>>log_file
#Status_Print $?
#
#dnf install nginx -y &>>log_file
#Status_Print $?
#
#cp nginx.conf /etc/nginx/nginx.conf &>>log_file
#Status_Print $?
#
#rm -rf /usr/share/nginx/html/* &>>log_file
#Status_Print $?
#
#rm -f /tmp/frontend.zip &>>log_file
#Status_Print $?
#
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip &>>log_file
#Status_Print $?
#
#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip &>>log_file
#Status_Print $?
#
#systemctl enable nginx
#systemctl restart nginx &>>log_file
#Status_Print $?



