##!/bin/bash
#source ./common.sh
#
#echo Install MySQL Service
#dnf install mysql-server -y
#Status_Print $?
#
#echo Start MySQL Service
#systemctl enable mysqld
#systemctl restart mysqld
#Status_Print $?
#
#echo Set MySQL Password
#mysql_secure_installation --set-root-pass RoboShop@1
#Status_Print $?


- name: Install MySQL Service
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL Service
  ansible.builtin.systemd_service:
    name: mysqld
    state: restarted
    enabled: true

- name: Set MySQL Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

